from bioinfo_1A import PatternCount

def FreqWords(text, k):
    Patterns = {}
    for i in range(len(text) - k + 1):
        pattern = text[i:i+k]
        count = PatternCount(text, pattern)
        Patterns.update({pattern : count})
    FreqPatterns = [k for k, v in Patterns.items() if v == max(Patterns.values())]
    return FreqPatterns

if __name__ == '__main__':

    full_text = '''TGGCATTGGACGGAAGTGGCATTGGGTAGACCCTTTCACTTGGTAGACCGACGGAAGGACGGAAGGACGGAAGGACGGAAGTGGCATTGGGTAGACCTGGCATTGTGGCATTGGACGGAAGGACGGAAGCTTTCACTTCTTTCACTTGGTAGACCCTTTCACTTTGGCATTGGGTAGACCGACGGAAGTAGCGTGTCTTTCACTTTAGCGTGTCTTTCACTTGGTAGACCTAGCGTGTGGTAGACCGGTAGACCCTTTCACTTTAGCGTGTGGTAGACCTAGCGTGTCTTTCACTTCTTTCACTTTAGCGTGTTGGCATTGGACGGAAGGGTAGACCCTTTCACTTTAGCGTGTCTTTCACTTTGGCATTGGGTAGACCGGTAGACCTAGCGTGTGGTAGACCCTTTCACTTCTTTCACTTCTTTCACTTTGGCATTGGACGGAAGTGGCATTGGGTAGACCTGGCATTGCTTTCACTTTGGCATTGCTTTCACTTGACGGAAGGACGGAAGGACGGAAGGGTAGACCTGGCATTGCTTTCACTTTAGCGTGTGACGGAAGCTTTCACTTGACGGAAGTGGCATTGTGGCATTGTAGCGTGTTGGCATTGGACGGAAGCTTTCACTTCTTTCACTTCTTTCACTTGGTAGACCTAGCGTGTTAGCGTGTTAGCGTGTTAGCGTGTTGGCATTGTGGCATTGCTTTCACTTGGTAGACCGACGGAAGTAGCGTGTTGGCATTGGACGGAAGTGGCATTGCTTTCACTTGGTAGACCGGTAGACCGGTAGACCCTTTCACTTGACGGAAGTAGCGTGTCTTTCACTTGGTAGACC
    13
    '''
    text, k, _ = full_text.split('\n')
    k = int(k)

    # print(text, k)

    for i in FreqWords(text, k):
        print(i, end = '\t')